// Enum => For actions types ( Constants )
export enum ActionTypes {
    GET_TICkETS = 'GET_TICKETS',
    GET_TICKETS_LOADING = 'GET_TICKETS_LOADING',
    GET_TICKETS_FAIL = 'GET_TICKETS_FAIL',
    DELETE_TICKET = 'DELETE_TICKET',
    DELETE_TICKET_FAIL = 'DELETE_TICKET_FAIL',
    EDIT_TICKET = 'EDIT_TICKET',
    ADD_TICKET_SUCCESS = 'ADD_TICKET_SUCCESS',
    ADD_TICKET_FAIL = 'ADD_TICKET_FAIL',
    UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS',
    UPDATE_TICKET_FAIL = 'UPDATE_TICKET_FAIL',
    UPDATE_TICKET_SERVER = 'UPDATE_TICKET_SERVER',
}